travis:
  secure:
    BINSTAR_TOKEN: Bv3XpaIko7VHYM/G7Kr3usvVoYYM8SswsmG4iyFxiStXKBk7RlKU5yq+KyFzQ3dZJgydDIi7H4a5S+JVTTPHiOmui+WXAGqkEgHZnqaOWVstQZOaxyc8/8WBjBpuRMsRu0A1nS9iy0JUky7QJ5VH2OvnbjlYjvdIWefVKLQF6ssXRqFXHNDLKP4nzcQ1zS4hEZgVEr//wWXnr3PH7HD/s/LaIhjrcasWlN205ItP5PWWO4JOoHuvyD2SiqJjNWUsFb8TER62qVy/3UJwRxSfFr5Mln8sibdjYpBzGoe+oRXUBfz11EQaoJmR5W2Spgq5ZT79jS3KKHvprufnikZd79JOFYz9zHk+Y0M8f3P5FX/ogU8tsEXRB6nEuPbv1GX6xUhdyMsl7ODKQ43AeAsn1/irqhBtb2VDWtAR/wQNxoFoP0+JxlJrciuf+jb+ts3snnO226Lg3wpzjK4FyNt7M2oooPnZ+fBdf3Ak2l4p005KjZwLIbqU9eV/JVqrfZxY31wX/yKTlBP5AsVdaxi9CcYtTcuy5JuYkIlyfBnzpaamb9IYBRxv+03m9wxjdJefkWV0bN1O3gze5mwNFA/8pJ1nDwtgOLrxd9VRTV8A2v6JUj37bu4Oem4ifv1/164GXcjhnBIE/hg9gRIaD8q7uT/VvSFLCZybu7U2L4WPaRc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
